name: modelling-dev
channels:
  - conda-forge
dependencies:
  - python=3.7.*
  - numpy >= 1.16
  - pandas >= 1
  - matplotlib >= 3.1
  - seaborn
  - xlrd
  - scipy
  - pytest
# Notebooks
  - jupyter
  - jupyterlab
  - nodejs
  - ipympl
# utilities
  - black
  - isort
  - tqdm
  - pyyaml
  - pip >= 19

  
